# Generated by Django 3.1 on 2020-09-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200912_1506'),
        ('contacts', '0002_auto_20200912_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Подія'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ПІБ'),
        ),
    ]
