# Generated by Django 3.1 on 2020-09-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/event', verbose_name='Картинка для івенту')),
                ('description', models.CharField(max_length=100, verbose_name='Опис картинки')),
            ],
            options={
                'verbose_name': 'Картинка події',
                'verbose_name_plural': 'Картинки подій',
            },
        ),
        migrations.CreateModel(
            name='EventPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Імя партнера')),
                ('image', models.ImageField(upload_to='images/event/partner', verbose_name='Фото партнера/Логотип компанії')),
                ('description', models.CharField(max_length=200, verbose_name='Коротко про партнера')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Посилання на детальнішу інформацію')),
            ],
            options={
                'verbose_name': 'Партнери подій',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Тег івенту',
                'verbose_name_plural': 'Теги івенту',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('location', models.CharField(blank=True, help_text='Місто/Вулиця/Номер будинку', max_length=200, null=True, verbose_name='Локація')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Час початку')),
                ('fb_event', models.CharField(blank=True, max_length=200, null=True, verbose_name='Посилання на подію у fb')),
                ('slug', models.SlugField(verbose_name='Посилання')),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='event_images', to='events.EventImage')),
                ('partner', models.ManyToManyField(blank=True, null=True, related_name='event_partner', to='events.EventPartner')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='event_tags', to='events.EventTag')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
            },
        ),
    ]
