# Generated by Django 3.1 on 2020-09-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_conducted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='top_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventimage'),
        ),
    ]
