# Generated by Django 3.1 on 2020-09-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_top_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images', verbose_name='Головне зображення події'),
        ),
    ]
