# Generated by Django 3.1 on 2020-08-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200828_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='top_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
