# Generated by Django 3.1 on 2020-08-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200828_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Короткий опис картинки')),
                ('image', models.ImageField(upload_to='article_images/', verbose_name='Картинка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Стаття')),
            ],
            options={
                'verbose_name': 'Картинка з статті',
                'verbose_name_plural': 'Картинки з статті',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='article',
        ),
        migrations.DeleteModel(
            name='Choise',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
