# Generated by Django 3.1 on 2020-09-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200828_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Картинка статті', 'verbose_name_plural': 'Картинки статті'},
        ),
    ]
