# Generated by Django 3.1 on 2020-09-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва групи')),
                ('image', models.ImageField(upload_to='images/group_logo', verbose_name='Лого групи')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
            },
        ),
        migrations.CreateModel(
            name='StudentIpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('ip_adress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ПІБ студента')),
                ('image', models.ImageField(upload_to='images/student_profile_photo', verbose_name='Портретне фото студента')),
                ('slug', models.SlugField(verbose_name='Посилання на студента')),
                ('about', models.TextField(verbose_name='Про студента')),
                ('group', models.ForeignKey(help_text='Група студента', on_delete=django.db.models.deletion.CASCADE, to='cabinet.group')),
                ('ip', models.ManyToManyField(blank=True, null=True, to='cabinet.StudentIpAddress')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
    ]
