# Generated by Django 3.1 on 2020-09-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20200909_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInfo',
            new_name='Student',
        ),
    ]
