# Generated by Django 3.1 on 2020-09-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20200912_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Час уроку')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклад',
            },
        ),
    ]
