# Generated by Django 3.1 on 2020-09-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_auto_20200914_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschedule',
            name='week_day',
            field=models.CharField(choices=[('Mon', 'Понеділок'), ('Tue', 'Вівторок'), ('Wed', 'Середа'), ('Thu', 'Четвер'), ('Fri', "П'ятниця"), ('Sat', 'Субота')], default='Mon', max_length=3, verbose_name='День тижня'),
        ),
    ]
