# Generated by Django 3.1 on 2020-09-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_auto_20200914_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedule',
            name='week_day',
            field=models.CharField(choices=[('Понеділок', 'Понеділок'), ('Вівторок', 'Вівторок'), ('Середа', 'Середа'), ('Четвер', 'Четвер'), ("П'ятниця", "П'ятниця"), ('Субота', 'Субота')], max_length=20, verbose_name='День тижня'),
        ),
    ]
