# Generated by Django 3.1 on 2020-09-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20200909_1027'),
        ('cabinet', '0008_auto_20200914_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentschedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='subject',
            field=models.ManyToManyField(to='cabinet.Subject', verbose_name='Предмет'),
        ),
        migrations.RemoveField(
            model_name='studentschedule',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to='persons.Teacher', verbose_name='Викладач'),
        ),
    ]
