# Generated by Django 3.1 on 2020-09-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20200909_1027'),
        ('cabinet', '0009_auto_20200914_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentschedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet.subject', verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='studentschedule',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentschedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.teacher', verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='studentschedule',
            name='week_day',
            field=models.CharField(choices=[('Понеділок', 'Понеділок'), ('Вівторок', 'Вівторок'), ('Середа', 'Середа'), ('Четвер', 'Четвер'), ("П'ятниця", "П'ятниця"), ('Субота', 'Субота')], default='Mon', max_length=20, verbose_name='День тижня'),
        ),
    ]
