# Generated by Django 3.1 on 2020-09-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_auto_20200914_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthw',
            name='makr',
            field=models.SmallIntegerField(default=5, verbose_name='Оцінка'),
        ),
    ]
