# Generated by Django 3.1 on 2020-09-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_studenthw_makr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenthw',
            old_name='makr',
            new_name='mark',
        ),
    ]
