# Generated by Django 3.1 on 2020-09-14 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_auto_20200914_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthw',
            options={'verbose_name': 'Журнал оцінок', 'verbose_name_plural': 'Журнал оцінок'},
        ),
        migrations.AlterField(
            model_name='studenthw',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.student'),
        ),
    ]
