# Generated by Django 3.1 on 2020-09-15 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_auto_20200914_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentschedule',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet.group', verbose_name='Група'),
            preserve_default=False,
        ),
    ]
