# Generated by Django 3.1 on 2020-09-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_studentschedule_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthw',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.subject'),
        ),
    ]
