# Generated by Django 3.1 on 2020-09-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='persons', verbose_name='Картинка проекту')),
                ('name', models.CharField(max_length=100, verbose_name='Короткий опис картинки')),
            ],
            options={
                'verbose_name': 'Картиники проекту',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=200, verbose_name='Назва спеціальності')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна адреса викладача')),
                ('image', models.ImageField(upload_to='persons/', verbose_name='Профільна фотографія викладача')),
                ('credo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Життєве кредо')),
                ('description', models.TextField(verbose_name='Інформація про викладача')),
                ('channel', models.CharField(blank=True, max_length=300, null=True, verbose_name='Канал комунікації з викладачем')),
                ('slug', models.SlugField(verbose_name='Посилання на викладача')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Місто народження')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('specialty', models.ManyToManyField(help_text='Спеціальності викладача', related_name='teacher_specialty', to='persons.Specialty')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва проекту')),
                ('description', models.TextField(verbose_name='Опис проекту')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Час початку проекту')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Час закінчення проекту')),
                ('ended', models.BooleanField(default=False, verbose_name='Проект закрито')),
                ('images', models.ManyToManyField(help_text='Картинки проекту', related_name='project_images', to='persons.ProjectImage')),
                ('specialty', models.ManyToManyField(help_text='Спеціальності проетку', related_name='project_specialty', to='persons.Specialty')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('image', models.ImageField(upload_to='persons/', verbose_name='Профільна фотографія випускника')),
                ('description', models.TextField(verbose_name='Інформація про випускника')),
                ('channel', models.CharField(blank=True, max_length=300, null=True, verbose_name='Канал комунікації з випускником')),
                ('slug', models.SlugField(verbose_name='Посилання на випускника')),
                ('specialty', models.ManyToManyField(help_text='Спеціальність, яку вивчав випускник', related_name='alumni_specialty', to='persons.Specialty')),
            ],
            options={
                'verbose_name': 'Випускник',
                'verbose_name_plural': 'Випускники',
            },
        ),
    ]
