# Generated by Django 3.1 on 2020-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Картинка проекту', 'verbose_name_plural': 'Картиники проекту'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='projects',
            field=models.ManyToManyField(help_text='Наукові роботи, проекти викладача', related_name='teacher_projects', to='persons.Project'),
        ),
    ]
