# Generated by Django 3.1 on 2020-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200906_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='channel',
            field=models.CharField(blank=True, help_text='в форматі: facebook.com/osint0', max_length=300, null=True, verbose_name='Канал комунікації з викладачем'),
        ),
    ]
